coop:
  rest:
    url: http://localhost:9090
ssm:
  name: iterop-sign-document
signer:
  admin:
    name: adam
    file: file:./infra/bclan/adam
  user:
    name: bob
    file: file:./infra/bclan/bob

server:
  port : 8888
